// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spimwaixjxkjauikpurc.supabase.co"; // updated project URL
// IMPORTANT: replace with your project's anon public key from Supabase → API Keys (anon)
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwaW13YWl4anhramF1aWtwdXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDY1MTEsImV4cCI6MjA3MjIyMjUxMX0.r4rxhbfyAsZLh3hnno8PdqF_0qEJQn8guK_C0l7a0Zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});